import NavbarLayout from '@/components/Navbar';
import { Layout } from '@/components/layout/Navbar/Layout';
import { getUltimos } from '@/helpers/getUltimos';
import { SocketContext } from '@/hooks/SocketContext';
import authMiddleware from '@/middleware/authMiddleware';
import { Card, Divider, Grid, Text } from '@nextui-org/react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import React, { useContext, useEffect, useState } from 'react'


const Cola = () => {

  const { socket } = useContext(SocketContext);
  const [tickets, setTickets] = useState([]);

  useEffect(() => {
    socket.on('ticket-asignado', (ticketsAsignados)=>{
      setTickets(ticketsAsignados)
    })
  
    return () => {
      socket.off('ticket-asignado')
    }
  }, [socket])

  useEffect(()=>{
    getUltimos().then((data)=>{
      setTickets(data.ultimos)
    });
  },[])
  

  return (
    <>
      <Head>
        <title>Cola</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <NavbarLayout>
            <Grid.Container gap={2} justify="center" css={{ padding: "25px 80px" }}>
              <Grid xs={12}>
                <Text h1> Cola de tickets</Text>
              </Grid>
              <Grid xs={6} direction='column'>
                {tickets.slice(0,5).map((item: any) => {
                  return (
                    <li style={{ listStyle: "none" }}>
                      <Card variant="bordered" css={{ padding: "0px 5px", marginBottom: 10 }}>
                        <Card.Body css={{ padding: "5px 5px" }}>
                          <Text h4 color='success'>Ticket: {item.numero}</Text>


                          <Divider css={{ marginBottom: 4 }} />
                          <Grid xs={12} direction='row' justify='space-between' css={{ padding: 0 }}>
                            <Text h6 color='warning'>Agente: {item.agente}</Text>
                            <Text h6 color='warning'>Escritorio: {item.escritorio}</Text>
                          </Grid>

                        </Card.Body>
                      </Card>
                    </li>
                  )
                })}
              </Grid>
              <Grid xs={6} direction='column'>
                <Divider style={{fontSize:20, fontWeight: "bold", marginBottom: 25}}>Historal</Divider>
                {tickets.slice(5).map((item: any) => {
                  return (
                    <li style={{ listStyle: "none" }}>
                      <Card variant="bordered" css={{ padding: "0px 5px", marginBottom: 10 }}>
                        <Card.Body css={{ padding: "5px 5px" }}>
                          <Text h4 color='success'>Ticket No: {item.numero}</Text>


                          <Divider css={{ marginBottom: 4 }} />
                          <Grid xs={12} direction='row' justify='space-between' css={{ padding: 0 }}>
                            <Text h6 color='warning'>Agente: {item.agente}</Text>
                            <Text h6 color='warning'>En el escritorio: {item.escritorio}</Text>
                          </Grid>

                        </Card.Body>
                      </Card>
                    </li>
                  )
                })}
              </Grid>
            </Grid.Container>
          </NavbarLayout>
        </Layout>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = authMiddleware(async () => {
  // Devuelva los props necesarios para su página
  return {
    props: {
      // ...
    },
  };
});

export default Cola;
