import NavbarLayout from '@/components/Navbar';
import { Layout } from '@/components/layout/Navbar/Layout';
import { SocketContext } from '@/hooks/SocketContext';
import authMiddleware from '@/middleware/authMiddleware';
import { Button, Grid, Text } from '@nextui-org/react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import React, { useContext, useState } from 'react'
import { ChevronRightCircle } from 'react-iconly';

const CrearTicket = () => {

  const { socket } = useContext(SocketContext);
  const [ticketNo, setTicketNo] = useState(undefined);

  const crearTicket = () => {
    socket.emit("solicitar-ticket", null, (ticket: any) => {
      setTicketNo(ticket.numero)
    })
  }

  return (
    <>
      <Head>
        <title>Crear Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <NavbarLayout>
            <Grid.Container gap={2} justify="center" css={{ padding: "25px 80px" }}>
              <Grid xs={12}>
                <Text h1>Presione el botón para generar un nuevo ticket</Text>
              </Grid>
              <Grid xs={12}>
                <Button
                  color="success"
                  flat
                  size="xl"
                  onPress={crearTicket}
                  iconRight={<ChevronRightCircle set="bold" primaryColor="#ffffff" />}
                >
                  Siguiente ticket
                </Button>
              </Grid>
            </Grid.Container>
            {
              ticketNo && (
                <Grid.Container gap={2} css={{ height: "400px" }} alignItems='center' justify='center'>
                  <Grid xs={12} direction='column' alignItems='center'>
                    <Text h2>Su número es:</Text>
                    <Text h1 color='success'>{ticketNo}</Text>
                  </Grid>
                </Grid.Container>
              )
            }
          </NavbarLayout>
        </Layout>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = authMiddleware(async () => {
  // Devuelva los props necesarios para su página
  return {
    props: {
      // ...
    },
  };
});

export default CrearTicket;