import FormIngreso from '@/components/FormIngreso';
import NavbarLayout from '@/components/Navbar';
import { Layout } from '@/components/layout/Navbar/Layout';
import Head from 'next/head';
import React from 'react'

const Ingreso = () => {
  return (
    <>
      <Head>
        <title>Ingreso</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <Layout>
        <NavbarLayout>
          <FormIngreso />
        </NavbarLayout>
      </Layout>
      </main>
    </>
  )
}


export default Ingreso;